Rock/Models/ApplicationType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Rock.Models
{
    public class ApplicationType
    {
        public int? Id { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

Rock/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Rock.Models
{
    public class Category
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(1,int.MaxValue,ErrorMessage ="Display order must be > 0")]
        public int DisplayOrder { get; set; }
    }
}

Rock/Models/ErrorViewModel.cs
using System;

namespace Rock.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rock/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Rock.Data;
using Rock.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rock.Controllers
{
    public class ApplicationTypeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ApplicationTypeController(ApplicationDbContext db)
        {
            _db = db;
           System.Diagnostics.Debug.WriteLine(_db);
        }
        public IActionResult Index()
        {
            IEnumerable<ApplicationType> objList = _db.ApplicationType;
            return View(objList);
        }
        //Get-Create
        public IActionResult Create()
        {

            return View();
        }
        //Post-Create
        [HttpPost]//Defined this method as Post action method 
        [ValidateAntiForgeryToken]//security token
        public IActionResult Create(ApplicationType obj)
        {
            if (ModelState.IsValid)//if condition checks is all defined in ApplicationType(Model) rules are valid

            _db.ApplicationType.Add(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");//Redirect to ApplicationType Index
        }
        //Get-Edit
        public IActionResult Edit(int Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.ApplicationType.Find(Id);

            if (obj == null) return NotFound();


            return View(obj);
        }
        //Post-Edit

        [HttpPost]//Defined this method as Post action method 
        [ValidateAntiForgeryToken]//security token
        public IActionResult Edit(ApplicationType obj)//We need Id parametr in Category obj for Update method correct functioning.Update is looking for Category entities by Id.
        {
            if (ModelState.IsValid)//if condition checks is all defined in Category(Model) rules are valid
            {
                _db.ApplicationType.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");//Redirect to Category Index}

            }
            return View(obj);
        }

        //Get-Delete
        public IActionResult Delete(int Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.ApplicationType.Find(Id);

            if (obj == null) return NotFound();


            return View(obj);
        }
        //Post-Delete

        [HttpPost]//Defined this method as Post action method 
        [ValidateAntiForgeryToken]//security token
        public IActionResult DeleteApplication(int Id)//We need Id parametr in Category obj for Update method correct functioning.Update is looking for Category entities by Id.
        {
            var obj = _db.ApplicationType.Find(Id);
            {
                _db.ApplicationType.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");//Redirect to Category Index}

            }

        }
    }
}

Rock/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Rock.Data;
using Rock.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rock.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objList = _db.Category;
            return View(objList);
        }
        //Get-Create
        public IActionResult Create()
        {

            return View();
        }
        //Post-Create
        [HttpPost]//Defined this method as Post action method 
        [ValidateAntiForgeryToken]//security token
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)//if condition checks is all defined in Category(Model) rules are valid
            {
                _db.Category.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");//Redirect to Category Index}

            }
            return View(obj);
        }
        //Get-Edit
        public IActionResult Edit(int Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Category.Find(Id);

            if (obj == null) return NotFound();


            return View(obj);
        }
        //Post-Edit

        [HttpPost]//Defined this method as Post action method 
        [ValidateAntiForgeryToken]//security token
        public IActionResult Edit(Category obj)//We need Id parametr in Category obj for Update method correct functioning.Update is looking for Category entities by Id.
        {
            if (ModelState.IsValid)//if condition checks is all defined in Category(Model) rules are valid
            {
                _db.Category.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");//Redirect to Category Index}

            }
            return View(obj);
        }

        //Get-Delete
        public IActionResult Delete(int Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Category.Find(Id);

            if (obj == null) return NotFound();


            return View(obj);
        }
        //Post-Delete

        [HttpPost]//Defined this method as Post action method 
        [ValidateAntiForgeryToken]//security token
        public IActionResult DeletePost(int Id)//We need Id parametr in Category obj for Update method correct functioning.Update is looking for Category entities by Id.
        {
            var obj = _db.Category.Find(Id);
            {
                _db.Category.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");//Redirect to Category Index}

            }
          
        }
    }
}

Rock/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rock.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Rock.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rock/Views/ApplicationType/Create.cshtml
@model Rock.Models.ApplicationType

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ApplicationType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Rock/Views/ApplicationType/Delete.cshtml
@model Rock.Models.ApplicationType

<form method="post" asp-action="DeleteApplication">
    <input asp-for="Id" hidden />@*We need this input with Id for correct functioning Edit action method in CategoryController*@
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Application</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

    @section Scripts {

        @{<partial name="_ValidationScriptsPartial" />}

    }
</form>

Rock/Views/ApplicationType/Edit.cshtml
@model Rock.Models.ApplicationType

<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />@*We need this input with Id for correct functioning Edit action method in CategoryController*@
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

    @section Scripts {

        @{<partial name="_ValidationScriptsPartial" />}

    }
</form>

Rock/Views/ApplicationType/Index.cshtml
@model IEnumerable<ApplicationType>

<div class=" container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Application Types
            </h2>
        </div>
        <div class="col-6 text-right"><a asp-controller="ApplicationType" asp-action="Create" class="btn btn-primary">Add application type</a></div>
    </div>

    <br /><br />

    @if (Model.Count() >= 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                       Application name
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="30%">@obj.Id</td>
                    <td width="50%">@obj.Name</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="ApplicationType" asp-action="Edit" asp-route-Id="@obj.Id" class="btn btn-primary mx-2 rounded"><i class="fas fa-edit"></i></a>
                            <a asp-controller="ApplicationType" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-2 rounded"><i class="fas fa-trash"></i></a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <p>Application dont exist</p>
    }

</div>

Rock/Views/Category/Create.cshtml
@model Rock.Models.Category

<form method="post" asp-action="Create">

    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control" />
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a  asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

    @section Scripts{ 

    @{<partial name="_ValidationScriptsPartial"/>}

    }


</form>

Rock/Views/Category/Delete.cshtml
@model Rock.Models.Category

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />@*We need this input with Id for correct functioning Edit action method in CategoryController*@
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

    @section Scripts {

        @{<partial name="_ValidationScriptsPartial" />}

    }
</form>

Rock/Views/Category/Edit.cshtml
@model Rock.Models.Category

<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />@*We need this input with Id for correct functioning Edit action method in CategoryController*@
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control" />
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

    @section Scripts {

        @{<partial name="_ValidationScriptsPartial" />}

    }
</form>

Rock/Views/Category/Index.cshtml
@model IEnumerable<Category>

<div class=" container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Category List
            </h2>
        </div>
        <div class="col-6 text-right"><a asp-controller="Category" asp-action="Create" class="btn btn-primary"><i class="fas fa-folder-plus mr-2"></i>Create new category</a></div>
    </div>

    <br /><br />

    @if (Model.Count() >0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Category Name
                    </th>
                    <th>
                        Display order
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="50%">@obj.Name</td>
                        <td width="30%">@obj.DisplayOrder</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Category" asp-action="Edit" asp-route-Id="@obj.Id" class="btn btn-primary mx-2 rounded"><i class="fas fa-edit"></i></a>
                                <a asp-controller="Category" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-2 rounded"><i class="fas fa-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <p>Category dont exist</p>
    }

</div>

Rock/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Home</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Rock/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rock</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rock</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">ApplicationType</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Rock - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>